---
# tasks file for linux_update
- name: Update apt cache for Ubuntu/Debian hosts if necessary, then upgrade all packages
  # when: ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "*"
    state: latest
    only_upgrade: true
  tags: ['packages']

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: linux_update_reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: linux_update_reboot_required_file.stat.exists and inventory_hostname is not in linux_update_manual_reboot_list

- name: Waiting for the machine to come back
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    port: 22
    delay: 15
  delegate_to: localhost
  become: false
  when: linux_update_reboot_required_file.stat.exists and inventory_hostname is not in linux_update_manual_reboot_list
