---
# tasks file for linux_update
- name: Update apt cache for Ubuntu hosts if necessary, then upgrade all packages
  when: ansible_distribution == 'Ubuntu'
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "*"
    state: latest
  tags: [ 'packages' ]

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true and inventory_hostname is not in manual_reboot_list  

- name: Waiting for the machine to come back
  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=30
  become: no
  when: reboot_required_file.stat.exists and inventory_hostname is not in manual_reboot_list